import { copyFile, mkdir, rm } from "node:fs/promises";
import path from "node:path";
import process from "process";

import esbuild from "esbuild";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const isProduction = process.argv.includes("--production");

const OUT_DIR = "dist";
const MANIFEST = "manifest.json";
const STYLES = "styles.css";

const cleanBuild = async () => {
	const generatedFiles = ["main.js", "main.js.map", MANIFEST, STYLES];
	await Promise.all(
		generatedFiles.map((filename) => rm(path.join(OUT_DIR, filename), { force: true })),
	);
};

const postBuild = async () => {
	await mkdir(OUT_DIR, { recursive: true });
	await Promise.all([
		copyFile(path.join(MANIFEST), path.join(OUT_DIR, MANIFEST)),
		copyFile(path.join(STYLES), path.join(OUT_DIR, STYLES)),
	]);
};

const buildOptions = {
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: ["obsidian", "electron"],
	format: "cjs",
	target: "es2016",
	logLevel: "info",
	sourcemap: isProduction ? false : "inline",
	treeShaking: true,
	outdir: OUT_DIR,
};

if (isProduction) {
	await cleanBuild();
	await esbuild.build(buildOptions);
	await postBuild();
} else {
	const ctx = await esbuild.context(buildOptions);
	await ctx.watch();
	await postBuild();
}
